name: sql-generator
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.4
  - ipython=8.25.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libcxx=17.0.6
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.18.0
  - python=3.11.9
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - asn1crypto==1.5.1
      - attrs==23.2.0
      - boto3==1.34.133
      - botocore==1.34.133
      - certifi==2024.6.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cryptography==42.0.8
      - dataclasses-json==0.6.7
      - distro==1.9.0
      - docstring-parser==0.16
      - filelock==3.15.4
      - frozenlist==1.4.1
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - instructor==1.3.3
      - jiter==0.4.2
      - jmespath==1.0.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.2.6
      - langchain-aws==0.1.8
      - langchain-community==0.2.5
      - langchain-core==0.2.10
      - langchain-openai==0.1.10
      - langchain-text-splitters==0.2.1
      - langsmith==0.1.82
      - markdown-it-py==3.0.0
      - marshmallow==3.21.3
      - mdurl==0.1.2
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - numpy==1.26.4
      - openai==1.35.3
      - orjson==3.10.5
      - pycparser==2.22
      - pydantic==2.7.4
      - pydantic-core==2.18.4
      - pyjwt==2.8.0
      - pyopenssl==24.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - rich==13.7.1
      - s3transfer==0.10.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - snowflake-connector-python==3.11.0
      - snowflake-sqlalchemy==1.5.3
      - sortedcontainers==2.4.0
      - sqlalchemy==1.4.52
      - tenacity==8.4.2
      - tiktoken==0.7.0
      - tomlkit==0.12.5
      - tqdm==4.66.4
      - typer==0.12.3
      - typing-inspect==0.9.0
      - urllib3==2.2.2
      - yarl==1.9.4
