# Settings for testing and evaluation scripts

db_connection: 
  connector: snowflake
  user: 'hemanth'
  password: 'hemanthsnowflake'
  account: rla01593
  database: FINCOPILOT_CDM_V3
  schema: ACCOUNTS_RECEIVABLE
  warehouse: COMPUTE_WH
  role: DATA_ENGINEER_ROLE

db_connection_dd:
  connector: snowflake
  user: FINCOPILOT_SVC_DEV_USER
  key_path: 'src/evaluation/svc_rsa_key_DEV.p8'
  account: JWB18000
  warehouse: BASE_WAREHOUSE_SMALL
  database: SNOWFLAKE
  schema: INFORMATION_SCHEMA
  role: SNOWFLAKE_ACCOUNTING_FINCOPILOT_APPLICATION_DEV
 



dependent_apis:
  table_selector:
    api_url: 'https://5rr67jq1f3.execute-api.us-east-1.amazonaws.com/test/configurations/metadata'

  prompt_extractor:
    api_url: 'https://qchxfxriu8.execute-api.us-east-1.amazonaws.com/dev/businessobjects/resolver'



evaluation:
  intermediate_results_path: 'outputs/intermediate_results/evaluation'