# Use the AWS Lambda base image for Python 3.10
FROM public.ecr.aws/lambda/python:3.10

RUN yum update -y && \
    yum install -y \
    gcc \
    gcc-c++ \
    make \
    ffmpeg \
    libsm6 \
    libxext6 \
    python3-pip \
    git \
    && yum clean all

# Copy requirements.txt to the Lambda task root
COPY . ${LAMBDA_TASK_ROOT}

# Install Python dependencies into the Lambda task root
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"


CMD [ "main.handler" ]
